### ISSUE TITLE
Callback was alreday called error

### ISSUE THREAD

**Issue by chenghung** [marcojonker/data-elevator-elasticsearch#3]
```
node ./data-elevator/elevator move top
/home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:985:32
    at /home/eddie/projects/nodejs/my_app/node_modules/data-elevator/lib/elevator-engine/elevator-engine.js:136:28
    at _getFloors (/home/eddie/projects/nodejs/my_app/node_modules/data-elevator/lib/elevator-engine/elevator-engine.js:39:16)
    at /home/eddie/projects/nodejs/my_app/node_modules/data-elevator/lib/elevator-engine/elevator-engine.js:135:17
    at nextTask (/home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:5208:14)
    at /home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:5202:13
    at apply (/home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:41:25)
    at /home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:76:12
    at /home/eddie/projects/nodejs/my_app/node_modules/async/dist/async.js:988:16
    at /home/eddie/projects/nodejs/my_app/node_modules/data-elevator/lib/elevator-engine/elevator-engine.js:130:28
```

**Comment by marcojonker** [comment]
Thank you for the notification. Cannot reproduce the error so I need some more information. What does your configuration file look like (except for the credentials of course)? And can you send me the content of your floor files?
